repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: local
    hooks:
      - id: pytest-coverage
        name: pytest-coverage
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push] # <-- Aquí le decimos que solo corra al hacer push
