"""add category to complaint

Revision ID: 1592935c8aeb
Revises: a0b652c77c23
Create Date: 2026-04-02 17:14:24.132800

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1592935c8aeb"
down_revision: Union[str, Sequence[str], None] = "a0b652c77c23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    complaintcategory = sa.Enum("ACADEMIC", "SECURITY", name="complaintcategory")
    complaintcategory.create(op.get_bind(), checkfirst=True)
    op.add_column("complaint", sa.Column("category", complaintcategory, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("complaint", "category")
    sa.Enum(name="complaintcategory").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
