"""add notification model

Revision ID: 2448c427c791
Revises: e7c2d1f8a349
Create Date: 2026-04-16 13:14:12.980986

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2448c427c791"
down_revision: Union[str, Sequence[str], None] = "e7c2d1f8a349"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column(
            "category", sa.Enum("REPORTS", name="notificationcategory"), nullable=False
        ),
        sa.Column(
            "event_type",
            sa.Enum(
                "COMPLAINT_SUBMITTED",
                "COMPLAINT_IN_PROGRESS",
                "COMPLAINT_RESOLVED",
                "COMPLAINT_REJECTED",
                name="notificationeventtype",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["id_user"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_id_user"), "notification", ["id_user"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_id_user"), table_name="notification")
    op.drop_table("notification")
    # ### end Alembic commands ###
