"""add is_private to club, club_join_request table, extra_id to notification

Revision ID: 29f0ff63081f
Revises: 43a070ebdf5a
Create Date: 2026-05-06 08:19:02.704253

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29f0ff63081f"
down_revision: Union[str, Sequence[str], None] = "43a070ebdf5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "club_join_request",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_club", sa.Integer(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="joinrequeststatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["id_club"], ["club.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["id_user"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id_club", "id_user"),
    )
    op.create_index(
        op.f("ix_club_join_request_id_club"),
        "club_join_request",
        ["id_club"],
        unique=False,
    )
    op.add_column(
        "club",
        sa.Column("is_private", sa.Boolean(), server_default="false", nullable=False),
    )
    op.drop_index(op.f("ix_club_message_club_created"), table_name="club_message")
    op.add_column("notification", sa.Column("extra_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification", "extra_id")
    op.create_index(
        op.f("ix_club_message_club_created"),
        "club_message",
        ["id_club", "created_at"],
        unique=False,
    )
    op.drop_column("club", "is_private")
    op.drop_index(op.f("ix_club_join_request_id_club"), table_name="club_join_request")
    op.drop_table("club_join_request")
    # ### end Alembic commands ###
