"""add club models

Revision ID: a0b652c77c23
Revises: 21e0e545d40c
Create Date: 2026-03-31 00:22:08.852064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0b652c77c23"
down_revision: Union[str, Sequence[str], None] = "21e0e545d40c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "club_category",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "club",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=False),
        sa.Column("image", sa.String(length=500), nullable=True),
        sa.Column("id_category", sa.Integer(), nullable=False),
        sa.Column("id_leader", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_category"],
            ["club_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_leader"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "club_member",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_club", sa.Integer(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_club"],
            ["club.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id_club", "id_user"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("club_member")
    op.drop_table("club")
    op.drop_table("club_category")
    # ### end Alembic commands ###
