"""add type id_building and classroom to complaint

Revision ID: a66424802494
Revises: dad232aa3c23
Create Date: 2026-04-12 19:50:58.371496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a66424802494"
down_revision: Union[str, Sequence[str], None] = "dad232aa3c23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    complainttype = sa.Enum("REPORT", "SUGGESTION", name="complainttype")
    complainttype.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "complaint",
        sa.Column(
            "type",
            complainttype,
            nullable=False,
            server_default="REPORT",
        ),
    )
    op.add_column("complaint", sa.Column("id_building", sa.Integer(), nullable=True))
    op.add_column(
        "complaint", sa.Column("classroom", sa.String(length=255), nullable=True)
    )
    op.create_foreign_key(
        None, "complaint", "building", ["id_building"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "complaint", type_="foreignkey")
    op.drop_column("complaint", "classroom")
    op.drop_column("complaint", "id_building")
    op.drop_column("complaint", "type")

    complainttype = sa.Enum("REPORT", "SUGGESTION", name="complainttype")
    complainttype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
