"""make_club_id_category_nullable

Revision ID: f2adf8fdec5d
Revises: 2a3b4c5d6e7f
Create Date: 2026-05-13 12:24:35.342901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2adf8fdec5d'
down_revision: Union[str, Sequence[str], None] = '2a3b4c5d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('club', 'id_category',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('club', 'id_category',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
